### PR TITLE
Add sliders

### PR DESCRIPTION
**Pull request by ivanovs-4**

### CODE REVIEW

**Comment by Gabriella439** [comment]
Thanks for doing this!  Let me try to fix the CI failure but if that takes too long I will merge this anyway

**Comment by Gabriella439** [comment]
I can publish a new release to Hackage if you don't have any other pending changes in mind

**Comment by ivanovs-4** [comment]
As you wish. I make it just to practice a little.

Thank you for all your articles!

**Comment by Gabriella439** [comment]
You're welcome! :)

**Pull request merged**
